Repository 4-Nuga/goods-goods-duck-front, pull requests merged in 2024-05, with the labels that each got.

#4 [MERGE] develop to main
  .env.example
  src/app/api/auth/[...nextauth]/options.ts
  src/app/api/auth/[...nextauth]/route.ts
  src/styles/next-auth.d.ts
Labels: 🌏 Deploy

#7 Design: 인트로 화면 퍼블리싱 (#6)
  .eslintcache
  .pnp.cjs
  src/app/(main)/layout.tsx
  src/app/(main)/page.tsx
  src/containers/main/Intro.tsx
  src/containers/main/IntroDuck.tsx
  src/containers/main/Title.tsx
Labels: 🎨 Html & CSS

#9 Design: 로그인 페이지 퍼블리싱
  .eslintignore
  .pnp.cjs
  next.config.mjs
  package.json
  public/images/appleLoginBtn.png
  public/images/googleLoginBtn.png
  public/images/kakaoLoginBtn.png
  public/images/naverLoginBtn.png
  public/svgs/loginContour.svg
  public/svgs/loginDuck.svg
  src/app/(member)/login/page.tsx
  src/containers/login/LoginForm.tsx
  src/containers/login/SocialForm.tsx
  src/styles/fonts.ts
  src/styles/tmp.css
  tsconfig.json
  yarn.lock
Labels: 🎨 Html & CSS

#10 Feat: Login 기능 구현
  .env.example
  .eslintcache
  .pnp.cjs
  .yarn/sdks/typescript/lib/tsserver.js
  .yarn/sdks/typescript/lib/tsserverlibrary.js
  package.json
  src/app/(member)/login/page.tsx
  src/app/api/auth/[...nextauth]/options.ts
  src/containers/login/LoginForm.tsx
  src/containers/login/SocialForm.tsx
  src/middleware.ts
  src/types/next-auth.d.ts
  src/utils/localStorage.ts
  yarn.lock
Labels: ✨ Feature, 🎨 Html & CSS

#21 Rename: 일부 파일 폴더 변경 및 port 번호 변경에 따른 파일 수정
  .env.example
  .pnp.cjs
  src/app/api/auth/[...nextauth]/options.ts
  src/containers/join/IdInput.tsx
  src/containers/join/JoinForm.tsx
  src/containers/join/NicknameInput.tsx
  src/containers/join/PhoneVerification.tsx
  src/containers/join/Pw2Input.tsx
  src/containers/join/PwInput.tsx
  src/containers/join/SelectCategory.tsx
  src/utils/api/memberFunctions.ts
Labels: 📬 API, ⚙ Setting

#23 Design: 카테고리 화면 퍼블리싱
  .pnp.cjs
  public/svgs/category/animation.svg
  public/svgs/category/animationColor.svg
  public/svgs/category/animationGo.svg
  public/svgs/category/baseball.svg
  public/svgs/category/baseballColor.svg
  public/svgs/category/baseballGo.svg
  public/svgs/category/kpop.svg
  public/svgs/category/kpopColor.svg
  public/svgs/category/kpopGo.svg
  src/containers/category/Category.tsx
Labels: 🎨 Html & CSS

#25 Feat: 마이페이지 인트로 퍼블리싱 및 데이터 페칭 설정
  public/svgs/duck/nonProfileDuck.svg
  public/svgs/duck/sampleDuck.svg
  src/app/(member)/join/page.tsx
  src/app/(member)/login/page.tsx
  src/app/api/auth/[...nextauth]/options.ts
  src/app/mypage/layout.tsx
  src/app/mypage/page.tsx
  src/components/Header/MyPageHeader.tsx
  src/containers/(member)/join/FirstBtnArea.tsx
  src/containers/(member)/join/IdInput.tsx
  src/containers/(member)/join/JoinForm.tsx
  src/containers/(member)/join/NicknameInput.tsx
  src/containers/(member)/join/PhoneVerification.tsx
  src/containers/(member)/join/ProfileImgArea.tsx
  src/containers/(member)/join/Pw2Input.tsx
  src/containers/(member)/join/PwInput.tsx
  src/containers/(member)/join/SecondBtnArea.tsx
  src/containers/(member)/join/SelectCategory.tsx
  src/containers/(member)/join/store.ts
  src/containers/(member)/login/LoginForm.tsx
  src/containers/(member)/login/SocialForm.tsx
  src/containers/mypage/ActivityArea.tsx
  src/containers/mypage/DuckPointArea.tsx
  src/containers/mypage/InfoArea.tsx
  src/containers/mypage/MannerDuckArea.tsx
  src/containers/mypage/TradeArea.tsx
  src/types/apiResponseType.ts
  src/types/mypageDataType.ts
  src/types/next-auth.d.ts
  src/utils/memberApi.ts
  src/utils/mypageApi.ts
Labels: 📬 API, 🎨 Html & CSS

#27 Design: 마이페이지 퍼블리싱 진행 중
  .pnp.cjs
  next.config.mjs
  src/app/duck-point/charge/page.tsx
  src/app/duck-point/details/page.tsx
  src/app/duck-point/layout.tsx
  src/app/layout.tsx
  src/app/mypage/bid/page.tsx
  src/app/mypage/page.tsx
  src/app/mypage/reviews/page.tsx
  src/app/mypage/sell/page.tsx
  src/app/mypage/settings/page.tsx
  src/app/mypage/update-password/page.tsx
  src/app/mypage/update-profile/page.tsx
  src/app/mypage/winning-bid/page.tsx
  src/app/review/[tradeId]/page.tsx
  src/components/Header/MyPageHeader.tsx
  src/components/Tab/BidTab.tsx
  src/components/Tab/MypageTabType.ts
  src/components/Tab/ReviewTab.tsx
  src/components/Tab/SellTab.tsx
  src/components/Tab/WinningTab.tsx
  src/containers/duck-point/Details.tsx
  src/containers/mypage/ActivityArea.tsx
  src/containers/mypage/InfoArea.tsx
  src/containers/mypage/TradeArea.tsx
  src/containers/mypage/store.ts
  src/middleware.ts
Labels: 🎨 Html & CSS

#29 Design: 홈 화면 퍼블리싱
  .pnp.cjs
  package.json
  public/svgs/duck/mainDuckPoint.svg
  public/svgs/header/below_arrow.svg
  public/svgs/header/logo.svg
  public/svgs/header/notification.svg
  public/svgs/header/search.svg
  public/svgs/icon/likeFalse.svg
  public/svgs/icon/likeTrue.svg
  public/svgs/intro/introDuck.svg
  public/svgs/intro/title.svg
  public/svgs/nav/chat.svg
  public/svgs/nav/fullinquiry.svg
  public/svgs/nav/home.svg
  public/svgs/nav/like.svg
  public/svgs/nav/mypage.svg
  public/svgs/nav/notification.svg
  src/app/(main)/page.tsx
  src/components/layout/Header.tsx
  src/components/layout/Nav.tsx
  src/containers/main/AdvertisingBanner.tsx
  src/containers/main/ComingSoon.tsx
  src/containers/main/ComingSoonTitle.tsx
  src/containers/main/Hits.tsx
  src/containers/main/HotInterest.tsx
  src/containers/main/Intro.tsx
  src/containers/main/IntroDuck.tsx
  src/containers/main/LiveAndHotItem.tsx
  src/containers/main/LiveBidding.tsx
  src/containers/main/SoonAndHitsItem.tsx
  src/containers/main/TagItem.tsx
  src/containers/main/Title.tsx
  src/containers/main/UserDuckPoint.tsx
  src/containers/main/UserHeader.tsx
  src/containers/main/UserProfile.tsx
  src/containers/notification/NotificationVisible.tsx
  src/dummydata/banner1.png
  src/dummydata/banner2.png
  src/dummydata/banner3.png
  src/dummydata/comingSoon.json
  src/dummydata/liveBidding.json
  src/dummydata/profile.png
  src/types/BannerType.ts
  src/types/LiveAndHotType.ts
  src/types/SoonAndHitsType.ts
  yarn.lock
Labels: 🎨 Html & CSS

#37 Design: 회원 관련 페이지 커스텀
  Dockerfile
  src/app/(member)/login/page.tsx
  src/containers/(member)/join/SelectCategory.tsx
  src/containers/(member)/join/store.ts
  src/containers/main/SoonAndHitsItem.tsx
Labels: ✨ Feature, 🎨 Html & CSS

#39 Refactor: 폴더 구조 변경
  src/app/(member)/join/page.tsx
  src/app/(member)/login/page.tsx
  src/containers/member/join/FirstBtnArea.tsx
  src/containers/member/join/IdInput.tsx
  src/containers/member/join/JoinForm.tsx
  src/containers/member/join/NicknameInput.tsx
  src/containers/member/join/PhoneVerification.tsx
  src/containers/member/join/ProfileImgArea.tsx
  src/containers/member/join/Pw2Input.tsx
  src/containers/member/join/PwInput.tsx
  src/containers/member/join/SecondBtnArea.tsx
  src/containers/member/join/SelectCategory.tsx
  src/containers/member/join/store.ts
  src/containers/member/login/LoginForm.tsx
  src/containers/member/login/SocialForm.tsx
  src/styles/globals.css
Labels: 🔨 Refactor
