Repository 4-Nuga/goods-goods-duck-front, pull requests merged in 2024-07, with the labels that each got.

#133 Refactor: 상품 등록, 좋아요 에러 방지 / 홈 css 수정
  src/app/(goods)/goods/[goodsCode]/page.tsx
  src/components/layout/RegistrationBtn.tsx
  src/components/layout/UpNav.tsx
  src/containers/category/Category.tsx
  src/containers/goods/detail/DetailInfo.tsx
  src/containers/goods/list/GoodsItem.tsx
  src/containers/goods/registration/GoodsForm.tsx
  src/containers/goods/registration/TagArea.tsx
  src/containers/main/Hits.tsx
  src/containers/main/HotInterest.tsx
  src/containers/main/LiveAndHotItem.tsx
  src/containers/main/LiveBidding.tsx
  src/containers/main/MainCategory.tsx
  src/containers/main/SoonAndHitsItem.tsx
  src/types/mainType.ts
Labels: 🔨 Refactor

#135 Feat: 거래 후기 작성, 목록 진행중
  public/svgs/duck/falseReviewDuck.svg
  public/svgs/duck/reviewDuck.svg
  src/app/mypage/reviews/page.tsx
  src/app/review/[tradeId]/page.tsx
  src/app/review/page.tsx
  src/components/layout/Nav.tsx
  src/containers/mypage/review/ReviewItem.tsx
  src/containers/mypage/review/ReviewList.tsx
  src/containers/review/ReviewForm.tsx
  src/containers/review/ReviewHeader.tsx
  src/types/etcApiDataType.ts
  src/utils/etcApiActions.ts
Labels: 📬 API, ✨ Feature, 🎨 Html & CSS

#137 Feat: 채팅방 및 채팅룸 상품정보 불러오기
  src/app/(chat)/chat-room/[chatRoomId]/page.tsx
  src/components/Chat/ConfirmModal.tsx
  src/components/Chat/NickName.tsx
  src/containers/chat/chat-list/ChatList.tsx
  src/containers/chat/chat-list/ChatRoomImage.tsx
  src/containers/chat/chat-list/LastChat.tsx
  src/containers/chat/chat-room/ChatView.tsx
  src/containers/chat/chat-room/GoToReviewBtn.tsx
  src/containers/chat/chat-room/_ChatSender.tsx
  src/containers/mypage/bid/BidContent.tsx
  src/containers/mypage/winning-bid/WinningContent.tsx
Labels: ✨ Feature

#138 Feat: 리뷰 데이터 패칭
  public/sw.js
  public/workbox-b1b34251.js
  public/workbox-dae32412.js
  src/app/review/page.tsx
  src/components/Header/MyPageHeader.tsx
  src/containers/mypage/review/ReviewItem.tsx
  src/containers/mypage/review/ReviewList.tsx
  src/containers/mypage/review/ReviewModal.tsx
  src/containers/review/ReviewForm.tsx
  src/containers/review/ReviewHeader.tsx
  src/types/etcApiDataType.ts
Labels: 📬 API, ✨ Feature, 🎨 Html & CSS

#139 Fix: 데이터 패칭 오류 해결
  public/sw.js
  src/containers/mypage/review/ReviewItem.tsx
  src/containers/mypage/review/ReviewModal.tsx
  src/containers/review/ReviewForm.tsx
  src/utils/etcApiActions.ts
Labels: 📬 API, 🐞 BugFix, 🔨 Refactor

#141 Refactor: 좋아요 수정, 기본이미지 s3 적용
  src/components/Btn/LikeBtn.tsx
  src/containers/goods/detail/BiddingUserItem.tsx
  src/containers/goods/detail/DetailInfo.tsx
  src/containers/goods/list/GoodsItem.tsx
  src/containers/main/LiveAndHotItem.tsx
  src/containers/main/SoonAndHitsItem.tsx
  src/containers/mypage/review/ReviewItem.tsx
  src/containers/review/ReviewForm.tsx
Labels: 🔨 Refactor

#145 Fix: 좋아요 오류 해결
  public/sw.js
  public/workbox-b1b34251.js
  public/workbox-dae32412.js
  src/containers/goods/detail/ConfirmModal.tsx
  src/containers/goods/detail/DeleteBtn.tsx
  src/containers/goods/list/GoodsItem.tsx
  src/containers/goods/registration/GoodsForm.tsx
  src/containers/main/LiveAndHotItem.tsx
  src/containers/main/SoonAndHitsItem.tsx
  src/containers/mypage/bid/BidContent.tsx
  src/containers/mypage/like/LikeItem.tsx
  src/containers/mypage/sell/SellContent.tsx
  src/containers/mypage/winning-bid/WinningContent.tsx
  src/utils/goodsApiActions.ts
Labels: 🐞 BugFix

#147 Feat: 이미지 webp 변환 코드 추가
  .env.example
  package.json
  public/sw.js
  src/app/mypage/notice/page.tsx
  src/components/Chat/NickName.tsx
  src/containers/chat/chat-list/ChatRoomImage.tsx
  src/containers/goods/detail/DetailDescription.tsx
  src/containers/goods/registration/GoodsForm.tsx
  src/containers/main/AdvertisingBanner.tsx
  src/containers/mypage/bid/BidContent.tsx
  src/utils/goodsApiActions.ts
  src/utils/uploadImage.ts
  yarn.lock
Labels: ✨ Feature

#149 Feat: css transition 추가
  package.json
  src/components/layout/SubHeader.tsx
  src/containers/category/Category.tsx
  src/containers/chat/chat-list/ChatListTopSection.tsx
  src/containers/chat/chat-room/ChatView.tsx
  src/containers/goods/list/GoodsItem.tsx
  src/containers/main/AdvertisingBanner.tsx
  src/containers/main/HotInterest.tsx
  src/containers/main/LiveBidding.tsx
  src/containers/main/MainCategory.tsx
  src/containers/main/SoonAndHitsItem.tsx
  src/containers/mypage/ActivityArea.tsx
  src/containers/mypage/DuckPointArea.tsx
  src/containers/mypage/InfoArea.tsx
  src/containers/mypage/MannerDuckArea.tsx
  src/containers/mypage/TradeArea.tsx
  src/containers/mypage/like/LikeItem.tsx
  yarn.lock
Labels: ✨ Feature, 🎨 Html & CSS

#152 HOTFIX: 소셜로그인 에러
  src/app/api/auth/[...nextauth]/options.ts
  src/containers/member/join/ProfileImgArea.tsx
Labels: 🐞 BugFix

#153 HOTFIX: 소셜 로그인
  public/sw.js
  public/workbox-dae32412.js
  src/containers/member/join/EasyForm.tsx
Labels: 🐞 BugFix
