Repository 4-Nuga/goods-goods-duck-front, pull requests merged in 2024-06, with the labels that each got.

#42 Feat: PWA 설정
  .eslintrc.json
  next.config.mjs
  package.json
  public/sw.js
  public/workbox-dae32412.js
  src/app/layout.tsx
  src/app/manifest.ts
  src/components/Modal/BasicAlert/index.tsx
  src/components/Modal/SelectAlert/index.tsx
  src/components/Modal/store.ts
  src/containers/member/join/FirstBtnArea.tsx
  src/containers/member/join/IdInput.tsx
  src/containers/member/join/JoinForm.tsx
  src/containers/member/join/NicknameInput.tsx
  src/containers/member/join/PhoneVerification.tsx
  src/containers/member/login/LoginForm.tsx
  tsconfig.json
  yarn.lock
Labels: 🐞 BugFix, ✨ Feature, ⚙ Setting

#45 Feat: 상품 등록 퍼블리싱, 이미지 등록 기능 구현
  src/app/(goods)/registration/page.tsx
  src/components/Btn/BackBtn.tsx
  src/components/layout/RegistrationBtn.tsx
  src/containers/goods/registration/CategoryArea.tsx
  src/containers/goods/registration/DescriptionArea.tsx
  src/containers/goods/registration/DurationModal.tsx
  src/containers/goods/registration/GoodsForm.tsx
  src/containers/goods/registration/ImageArea.tsx
  src/containers/goods/registration/PeriodArea.tsx
  src/containers/goods/registration/RegistrationHeader.tsx
  src/containers/goods/registration/TagArea.tsx
  src/containers/goods/registration/TimeModal.tsx
  src/containers/goods/registration/TradeTypeArea.tsx
  src/containers/goods/registration/WeekModal.tsx
  src/containers/goods/registration/store.ts
Labels: ✨ Feature, 🎨 Html & CSS

#44 Feat: Alert 모달, 회원가입 성공 모달 기능 및 퍼블리싱 구현
  src/app/@modal/(.)(member)/join/modal.tsx
  src/app/@modal/(.)(member)/join/page.tsx
  src/app/@modal/default.tsx
  src/components/Modal/BasicAlert/index.tsx
  src/components/Modal/SelectAlert/index.tsx
  src/containers/member/join/JoinSuccessModal.tsx
  src/containers/member/join/SelectCategory.tsx
Labels: ✨ Feature, 🎨 Html & CSS

#48 Refactor: 같은 페이지 type들 한 파일로 정리, 경로 수정
  src/containers/main/AdvertisingBanner.tsx
  src/containers/main/ComingSoon.tsx
  src/containers/main/Hits.tsx
  src/containers/main/HotInterest.tsx
  src/containers/main/LiveAndHotItem.tsx
  src/containers/main/LiveBidding.tsx
  src/containers/main/SoonAndHitsItem.tsx
  src/containers/main/TagItem.tsx
  src/containers/notification/NotificationContent.tsx
  src/containers/notification/NotificationModal.tsx
  src/containers/search/RecentSearch.tsx
  src/containers/search/SearchModal.tsx
  src/types/BannerType.ts
  src/types/KeywordType.ts
  src/types/LiveAndHotType.ts
  src/types/headerType.ts
  src/types/mainType.ts
Labels: 🔨 Refactor

#47 Design: 신고 화면 퍼블리싱
  src/app/complain/page.tsx
  src/containers/complain/CheckList.tsx
  src/containers/complain/ComplainForm.tsx
  src/containers/complain/ComplainHeader.tsx
  src/containers/complain/ReasonArea.tsx
Labels: 🎨 Html & CSS

#50 Design: 판매자 정보 화면 퍼블리싱
  src/app/(goods)/seller/page.tsx
  src/containers/goods/seller/SellerHeader.tsx
  src/containers/goods/seller/SellerMannerDuck.tsx
  src/containers/goods/seller/SellerProfile.tsx
  src/containers/goods/seller/SellerReview.tsx
  src/dummydata/sellerReview.json
Labels: 🎨 Html & CSS

#52 Design: 굿즈 전체 조회 화면 퍼블리싱
  .vscode/settings.json
  public/svgs/icon/checkFalse.svg
  public/svgs/icon/checkTrue.svg
  src/app/(goods)/goods/layout.tsx
  src/app/(goods)/goods/page.tsx
  src/components/layout/Nav.tsx
  src/containers/goods/list/GoodsItem.tsx
  src/containers/goods/list/GoodsList.tsx
  src/containers/goods/registration/GoodsForm.tsx
  src/containers/goods/registration/TagArea.tsx
  src/containers/goods/seller/SellerReview.tsx
  src/dummydata/goodsItem.json
  src/dummydata/goodsList.json
  src/types/goodsType.ts
Labels: 🎨 Html & CSS

#57 Fix: use client
  src/containers/mypage/BidList.tsx
  src/containers/mypage/LikeList.tsx
  src/containers/mypage/SellList.tsx
  src/containers/mypage/WinningBidList.tsx
Labels: 🐞 BugFix

#58 Fix: build Error
  public/sw.js
  src/containers/member/join/NicknameInput.tsx
Labels: 🐞 BugFix

#59 Design: 굿즈 상세 화면 퍼블리싱
  public/svgs/duck/biddingDuck.svg
  public/svgs/duck/descriptionDuck.svg
  public/svgs/duck/etcDuck.svg
  public/svgs/icon/homeColor.svg
  public/svgs/icon/nextBtn.svg
  public/svgs/icon/prevBtn.svg
  src/app/(goods)/goods-detail/layout.tsx
  src/app/(goods)/goods-detail/page.tsx
  src/app/(goods)/goods/layout.tsx
  src/components/layout/Nav.tsx
  src/components/layout/UpNav.tsx
  src/containers/goods/detail/BiddingBtn.tsx
  src/containers/goods/detail/BiddingModal.tsx
  src/containers/goods/detail/DetailDescription.tsx
  src/containers/goods/detail/DetailHeader.tsx
  src/containers/goods/detail/DetailImageArea.tsx
  src/containers/goods/detail/DetailInfo.tsx
  src/containers/goods/detail/EtcArea.tsx
  src/containers/goods/list/GoodsList.tsx
  src/types/goodsType.ts
Labels: 🎨 Html & CSS

#60 Refactor: 홈 화면 반응형으로 수정
  public/svgs/duck/idol-duck.svg
  public/sw.js
  public/workbox-b1b34251.js
  src/components/layout/Header.tsx
  src/components/layout/Nav.tsx
  src/components/layout/RegistrationBtn.tsx
  src/components/layout/UpNav.tsx
  src/containers/main/AdvertisingBanner.tsx
  src/containers/main/ComingSoon.tsx
  src/containers/main/Hits.tsx
  src/containers/main/HotInterest.tsx
  src/containers/main/LiveAndHotItem.tsx
  src/containers/main/LiveBidding.tsx
  src/containers/main/SoonAndHitsItem.tsx
  src/containers/main/TagItem.tsx
  src/dummydata/comingSoon.json
  src/dummydata/liveBidding.json
  src/styles/swiper.css
Labels: 🎨 Html & CSS, 🔨 Refactor

#61 Refactor: 신고 화면 유저, 굿즈로 구분 완료, 굿즈 상세랑 화면 연결
  src/app/(complain)/goods-complain/page.tsx
  src/app/(complain)/layout.tsx
  src/app/(complain)/user-complain/page.tsx
  src/app/(goods)/seller/page.tsx
  src/app/complain/page.tsx
  src/containers/complain/CheckList.tsx
  src/containers/complain/ComplainForm.tsx
  src/containers/complain/ReasonArea.tsx
  src/containers/goods/detail/EtcArea.tsx
  src/containers/goods/seller/SellerHeader.tsx
Labels: 🎨 Html & CSS, 🔨 Refactor

#65 Refactor: 서버 액션 리팩토링, 로그인/회원가입 모달 삭제 및 출력 형식 변경
  src/app/api/auth/[...nextauth]/options.ts
  src/components/Modal/BasicAlert/index.tsx
  src/containers/member/join/FirstBtnArea.tsx
  src/containers/member/join/IdInput.tsx
  src/containers/member/join/JoinForm.tsx
  src/containers/member/join/JoinSuccessModal.tsx
  src/containers/member/join/NicknameInput.tsx
  src/containers/member/join/PhoneVerification.tsx
  src/containers/member/join/ProfileImgArea.tsx
  src/containers/member/join/Pw2Input.tsx
  src/containers/member/join/PwInput.tsx
  src/containers/member/join/Pwd2Input.tsx
  src/containers/member/join/PwdInput.tsx
  src/containers/member/join/SecondBtnArea.tsx
  src/containers/member/join/SelectCategory.tsx
  src/containers/member/join/store.ts
  src/containers/member/login/LoginForm.tsx
  src/containers/member/login/SocialForm.tsx
  src/containers/member/login/store.ts
  src/containers/mypage/InfoArea.tsx
  src/containers/mypage/MannerDuckArea.tsx
  src/containers/mypage/UpdateNickname.tsx
  src/middleware.ts
  src/types/next-auth.d.ts
  src/utils/authApiActions.ts
  src/utils/goodsApiActions.ts
  src/utils/joinValidateCheck.ts
  src/utils/memberApiActions.ts
Labels: 📬 API, ✨ Feature, 🎨 Html & CSS, 🔨 Refactor

#63 Feat: 판매자 시점 퍼블리싱, 타이머 기능 구현, 일부 데이터 패칭 진행중
  public/svgs/duck/biddingConfirmDuck.svg
  src/app/(goods)/goods-detail/page.tsx
  src/app/(goods)/goods/[goodsCode]/layout.tsx
  src/app/(goods)/goods/[goodsCode]/page.tsx
  src/components/layout/Nav.tsx
  src/components/layout/RegistrationBtn.tsx
  src/containers/goods/detail/BiddingModal.tsx
  src/containers/goods/detail/BiddingPreview.tsx
  src/containers/goods/detail/BiddingUserItem.tsx
  src/containers/goods/detail/ConfirmModal.tsx
  src/containers/goods/detail/ConfirmationBtn.tsx
  src/containers/goods/detail/DeleteBtn.tsx
  src/containers/goods/detail/DetailDescription.tsx
  src/containers/goods/detail/DetailInfo.tsx
  src/containers/goods/detail/EtcArea.tsx
  src/containers/goods/detail/Timer.tsx
  src/containers/goods/detail/ToTalArea.tsx
  src/containers/goods/list/GoodsItem.tsx
  src/types/goodsType.ts
  src/utils/goodsDetailApiActions.ts
Labels: 📬 API, ✨ Feature, 🎨 Html & CSS

#69 Fix: 로그인 에러
  .eslintrc.json
  package.json
  public/firebase-messaging-sw.js
  src/app/api/auth/[...nextauth]/options.ts
  src/app/firebase.config.ts
  src/app/layout.tsx
  src/containers/member/join/JoinForm.tsx
  src/containers/member/join/ProfileImgArea.tsx
  src/containers/member/join/store.ts
  src/containers/member/login/LoginForm.tsx
  src/containers/member/login/SocialForm.tsx
  src/containers/member/login/store.ts
  src/containers/mypage/InfoArea.tsx
  src/utils/uploadImage.ts
  yarn.lock
Labels: 🐞 BugFix

#70 Fix: 소셜 로그인 / 빌드 에러
  src/app/mypage/update-profile/page.tsx
Labels: 📬 API, 🐞 BugFix

#72 Feat: 소셜 로그인 간편 회원가입
  src/app/(member)/find-info/page.tsx
  src/app/(member)/join/page.tsx
  src/app/api/auth/[...nextauth]/options.ts
  src/containers/member/join/EasyForm.tsx
  src/containers/member/join/FullForm.tsx
  src/containers/member/join/JoinFormArea.tsx
  src/containers/member/join/NicknameInput.tsx
  src/containers/member/join/ProfileImgArea.tsx
  src/containers/member/join/SelectCategory.tsx
  src/containers/member/join/store.ts
  src/containers/mypage/InfoArea.tsx
  src/types/next-auth.d.ts
Labels: ✨ Feature, 🎨 Html & CSS

#73 Feat: 소셜 로그인 관련 로직
  src/app/api/auth/[...nextauth]/options.ts
  src/containers/member/join/EasyForm.tsx
  src/containers/member/join/FullForm.tsx
  src/containers/member/join/NicknameInput.tsx
  src/containers/member/join/PhoneVerification.tsx
  src/containers/member/login/LoginForm.tsx
  src/utils/authApiActions.ts
Labels: 📬 API, ✨ Feature, 🎨 Html & CSS

#74 FIx: 로그인 에러
  src/app/(member)/find-info/page.tsx
  src/containers/member/join/EasyForm.tsx
  src/containers/member/join/JoinFormArea.tsx
  src/containers/member/join/PhoneVerification.tsx
Labels: 🐞 BugFix

#76 Fix: 회원가입 모달
  src/containers/member/join/EasyForm.tsx
  src/containers/member/join/FullForm.tsx
  src/containers/member/join/JoinFormArea.tsx
Labels: 🐞 BugFix

#75 Feat: 상품 등록 수정, 상품 상세 데이터 패칭 진행중
  public/svgs/duck/noImageDuck.svg
  src/app/(goods)/goods/[goodsCode]/page.tsx
  src/components/layout/Header.tsx
  src/containers/goods/detail/BiddingPreview.tsx
  src/containers/goods/detail/ConfirmModal.tsx
  src/containers/goods/detail/ConfirmationBtn.tsx
  src/containers/goods/detail/DeleteBtn.tsx
  src/containers/goods/detail/DetailDescription.tsx
  src/containers/goods/detail/DetailImageArea.tsx
  src/containers/goods/detail/DetailInfo.tsx
  src/containers/goods/detail/EtcArea.tsx
  src/containers/goods/detail/ToTalArea.tsx
  src/containers/goods/registration/GoodsForm.tsx
  src/containers/goods/registration/store.ts
  src/middleware.ts
  src/types/goodsType.ts
  src/utils/goodsDetailApiActions.ts
  src/utils/registrationApiActions.ts
  src/utils/uploadImage.ts
Labels: 📬 API, ✨ Feature

#79 Fix: 프로필 업데이트 수정
  src/app/api/auth/[...nextauth]/options.ts
  src/app/mypage/update-profile/page.tsx
  src/containers/mypage/store.ts
  src/containers/mypage/update-profile/UpdateFavCategory.tsx
  src/containers/mypage/update-profile/UpdateNickname.tsx
  src/containers/mypage/update-profile/UpdateProfileForm.tsx
  src/containers/mypage/update-profile/UpdateProfileImage.tsx
  src/containers/mypage/update-profile/store.ts
  src/utils/memberApiActions.ts
Labels: 📬 API, 🐞 BugFix

#78 Feat: Header
  firebase-messaging-sw.js
  src/app/firebase.config.ts
  src/components/layout/Header.tsx
  src/components/layout/store.ts
  src/containers/main/notification/NotificationContent.tsx
  src/containers/main/notification/NotificationModal.tsx
  src/containers/main/search/RecentSearch.tsx
  src/containers/main/search/SearchForm.tsx
  src/containers/main/search/SearchModal.tsx
  src/containers/main/search/SearchResult.tsx
  src/containers/main/search/store.ts
  src/containers/member/login/LoginForm.tsx
  src/containers/notification/NotificationContent.tsx
  src/containers/notification/NotificationModal.tsx
  src/containers/notification/NotificationVisible.tsx
  src/containers/search/SearchForm.tsx
  src/containers/search/SearchModal.tsx
  src/containers/search/SearchVisible.tsx
  src/types/headerType.ts
  src/types/notiApiDataType.ts
  src/types/readApiDataType.ts
  src/utils/notificationApiActions.ts
  src/utils/readsApiActions.ts
Labels: 📬 API, ✨ Feature, 🎨 Html & CSS

#82 Fix: 빌드 에러 해결
  public/sw.js
  src/containers/main/MainCategory.tsx
Labels: 🐞 BugFix

#83 Fix: update Data
  firebase-messaging-sw.js
  src/app/api/auth/[...nextauth]/options.ts
  src/app/api/auth/[...nextauth]/route.ts
  src/app/mypage/update-password/page.tsx
  src/components/Modal/BasicAlert/index.tsx
  src/components/Modal/store.ts
  src/containers/member/login/LoginForm.tsx
  src/containers/mypage/update-password/ChangePasswordForm.tsx
  src/containers/mypage/update-password/NewPwdInput.tsx
  src/containers/mypage/update-password/NewPwdInput2.tsx
  src/containers/mypage/update-password/PwdInput.tsx
  src/containers/mypage/update-password/store.ts
  src/containers/mypage/update-profile/UpdateNickname.tsx
  src/containers/mypage/update-profile/UpdateProfileForm.tsx
  src/containers/mypage/update-profile/store.ts
  src/types/memberApiDataType.ts
  src/types/next-auth.d.ts
  src/utils/authApiActions.ts
  src/utils/joinValidateCheck.ts
  src/utils/memberApiActions.ts
Labels: 📬 API, 🐞 BugFix, ✨ Feature, 🎨 Html & CSS

#85 Feat: 마이페이지 데이터
  src/app/api/auth/[...nextauth]/options.ts
  src/containers/mypage/update-password/ChangePasswordForm.tsx
  src/containers/mypage/update-profile/UpdateFavCategory.tsx
  src/containers/mypage/update-profile/UpdateNickname.tsx
  src/containers/mypage/update-profile/UpdateProfileForm.tsx
  src/containers/mypage/update-profile/store.ts
  src/utils/memberApiActions.ts
Labels: 📬 API, 🐞 BugFix, ✨ Feature

#86 Feat: 판매자 정보 조회 데이터 패칭
  public/svgs/duck/mannerDuckLevel1.svg
  public/svgs/duck/mannerDuckLevel2.svg
  public/svgs/duck/mannerDuckLevel3.svg
  public/svgs/duck/mannerDuckLevel4.svg
  public/svgs/duck/mannerDuckLevel5.svg
  public/sw.js
  src/app/(goods)/seller/page.tsx
  src/containers/goods/detail/EtcArea.tsx
  src/containers/goods/seller/SellerHeader.tsx
  src/containers/goods/seller/SellerMannerDuck.tsx
  src/containers/goods/seller/SellerProfile.tsx
  src/containers/goods/seller/SellerReview.tsx
  src/types/goodsType.ts
  src/utils/goodsDetailApiActions.ts
Labels: 📬 API, ✨ Feature

#88 Fix: 프로필 에러 수정
  src/app/mypage/update-password/page.tsx
  src/containers/mypage/update-password/ChangePasswordForm.tsx
  src/containers/mypage/update-password/NewPwdInput.tsx
  src/containers/mypage/update-password/NewPwdInput2.tsx
  src/containers/mypage/update-password/PwdInput.tsx
  src/containers/mypage/update-profile/UpdateProfileForm.tsx
  src/containers/mypage/update-profile/UpdateProfileImage.tsx
  src/middleware.ts
Labels: 📬 API, 🐞 BugFix

#90 Feat: 결제 시스템 테스트 연결
  src/app/duck-point/charge/page.tsx
  src/containers/duck-point/PointChargeForm.tsx
  src/containers/mypage/DuckPointArea.tsx
  src/types/memberApiDataType.ts
  src/utils/memberApiActions.ts
Labels: 📬 API, ✨ Feature

#91 Feat: 마이페이지 매너덕 조회 및 덕포인트 사용 내역 조회
  src/containers/duck-point/DetailContent.tsx
  src/containers/mypage/MannerDuckArea.tsx
  src/utils/memberApiActions.ts
Labels: 📬 API, ✨ Feature

#92 Feat: 무한 스크롤 진행중, 홈 화면 좋아요 callBackUrl로 수정
  package.json
  src/app/(main)/animation/page.tsx
  src/app/(main)/baseball/page.tsx
  src/app/(main)/idol/page.tsx
  src/containers/goods/list/GoodsItem.tsx
  src/containers/goods/list/GoodsList.tsx
  src/containers/main/LiveAndHotItem.tsx
  src/containers/main/SoonAndHitsItem.tsx
  src/containers/main/UserDuckPoint.tsx
  src/containers/main/UserHeader.tsx
  src/containers/main/UserProfile.tsx
  src/types/goodsType.ts
  src/utils/goodsListApiActions.ts
  yarn.lock
Labels: 📬 API, ✨ Feature, 🔨 Refactor

#95 Feat: 굿즈 신고 기능
  src/app/(complain)/goods-complain/page.tsx
  src/containers/complain/CheckList.tsx
  src/containers/complain/ComplainForm.tsx
  src/containers/complain/ReasonArea.tsx
  src/containers/complain/store.ts
Labels: 📬 API, ✨ Feature

#96 Feat: 유저 및 굿즈 신고 기능
  src/app/(complain)/user-complain/page.tsx
  src/app/(goods)/goods/[goodsCode]/page.tsx
  src/containers/complain/CheckList.tsx
  src/containers/complain/ComplainForm.tsx
  src/containers/complain/store.ts
  src/containers/mypage/MannerDuckArea.tsx
  src/utils/etcApiActions.ts
Labels: 📬 API, ✨ Feature, 🔨 Refactor

#97 Fix: Suspence
  src/containers/complain/ComplainForm.tsx
  src/containers/member/join/PhoneVerification.tsx
Labels: 🐞 BugFix

#98 Refactor: 상품 요약 조회 데이터 패칭
  public/sw.js
  src/containers/complain/ComplainForm.tsx
  src/containers/goods/list/GoodsItem.tsx
  src/containers/goods/list/GoodsList.tsx
Labels: 📬 API, 🔨 Refactor

#99 Fix: params
  public/sw.js
  public/workbox-dae32412.js
  src/app/(complain)/goods-complain/page.tsx
  src/app/(complain)/user-complain/page.tsx
  src/containers/complain/ComplainForm.tsx
Labels: 🐞 BugFix

#102 Feat: Toast
  public/sw.js
  src/app/layout.tsx
  src/components/Modal/BasicAlert/index.tsx
  src/components/Modal/store.ts
  src/components/Toast/index.tsx
  src/components/Toast/store.ts
  src/containers/complain/ComplainForm.tsx
  src/containers/goods/detail/DetailHeader.tsx
  src/containers/goods/registration/GoodsForm.tsx
  src/containers/goods/registration/ImageArea.tsx
  src/containers/goods/registration/PeriodArea.tsx
  src/containers/goods/registration/TagArea.tsx
  src/containers/member/join/PhoneVerification.tsx
  src/containers/member/join/ProfileImgArea.tsx
  src/containers/member/login/LoginForm.tsx
  src/containers/mypage/update-password/ChangePasswordForm.tsx
Labels: ✨ Feature, 🎨 Html & CSS

#103 Feat: FCM 로직 수정 중
  src/containers/member/login/LoginForm.tsx
  src/utils/memberApiActions.ts
  src/utils/notificationApiActions.ts
Labels: 🐞 BugFix

#108 Feat: 입찰, 낙찰, 삭제 데이터 패칭, 판매자 정보 패칭 수정
  src/app/(goods)/goods/[goodsCode]/page.tsx
  src/containers/goods/detail/BiddingBtn.tsx
  src/containers/goods/detail/BiddingModal.tsx
  src/containers/goods/detail/BiddingPreview.tsx
  src/containers/goods/detail/BiddingUserItem.tsx
  src/containers/goods/detail/ConfirmModal.tsx
  src/containers/goods/detail/ConfirmationBtn.tsx
  src/containers/goods/detail/DeleteBtn.tsx
  src/containers/goods/seller/SellerMannerDuck.tsx
  src/types/goodsType.ts
  src/utils/goodsDetailApiActions.ts
Labels: 📬 API, ✨ Feature

#109 Refactor: 충전 시간 업데이트 / 페이지네이션 일부 디자인 수정
  src/components/Modal/BasicAlert/index.tsx
  src/components/Pagination/index.tsx
  src/containers/duck-point/DetailContent.tsx
  src/containers/main/notification/NotificationModal.tsx
  src/containers/main/search/SearchResult.tsx
  src/containers/mypage/BidList.tsx
  src/containers/mypage/LikeList.tsx
  src/containers/mypage/SellList.tsx
  src/containers/mypage/WinningBidList.tsx
  src/containers/mypage/update-profile/UpdateNickname.tsx
  src/containers/mypage/update-profile/UpdateProfileForm.tsx
Labels: ✨ Feature, 🔨 Refactor

#105 Feat: 채팅 기능 개발
  package.json
  public/icons/tempProfile.png
  src/app/(chat)/chat-list/layout.tsx
  src/app/(chat)/chat-list/page.tsx
  src/app/(chat)/chat-room/[chatRoomId]/layout.tsx
  src/app/(chat)/chat-room/[chatRoomId]/page.tsx
  src/components/Btn/button.tsx
  src/components/Chat/ChatRoomPreview.tsx
  src/components/Chat/Loading.tsx
  src/components/Chat/NickName.tsx
  src/components/Text/textarea.tsx
  src/components/layout/Nav.tsx
  src/components/layout/SubHeader.tsx
  src/containers/chat/chat-list/ChatList.tsx
  src/containers/chat/chat-list/ChatListTopSection.tsx
  src/containers/chat/chat-list/ChatRoomImage.tsx
  src/containers/chat/chat-list/LastChat.tsx
  src/containers/chat/chat-room/ChatProfileImage.tsx
  src/containers/chat/chat-room/ChatView.tsx
  src/containers/chat/chat-room/ChatViewReceiverCard.tsx
  src/containers/chat/chat-room/ChatViewSenderCard.tsx
  src/containers/chat/chat-room/_ChatSender.tsx
  yarn.lock
Labels: ✨ Feature

#110 Fix: 채팅 기능 bug 수정
  src/components/Btn/button.tsx
  src/containers/chat/chat-room/ChatView.tsx
Labels: ✨ Feature

#111 Refactor: 이미지 불러오는 방식 변경
  public/images/basicImage.png
  src/components/layout/Header.tsx
  src/components/layout/Nav.tsx
  src/components/layout/RegistrationBtn.tsx
  src/components/layout/UpNav.tsx
  src/containers/category/Category.tsx
  src/containers/category/CategorySelection.tsx
  src/containers/chat/chat-list/ChatList.tsx
  src/containers/main/Hits.tsx
  src/containers/main/HotInterest.tsx
  src/containers/main/LiveAndHotItem.tsx
  src/containers/main/LiveBidding.tsx
  src/containers/main/MainCategory.tsx
  src/containers/main/SoonAndHitsItem.tsx
  src/containers/main/UserDuckPoint.tsx
  src/containers/main/UserProfile.tsx
  src/types/mainType.ts
Labels: 📬 API, 🔨 Refactor

#112 Design: rounded 추가
  src/containers/main/LiveAndHotItem.tsx
  src/containers/main/SoonAndHitsItem.tsx
Labels: 🎨 Html & CSS

#113 Refactor: 이미지 불러오는 방식 수정
  src/containers/chat/chat-list/ChatList.tsx
  src/containers/goods/list/GoodsItem.tsx
  src/types/goodsType.ts
Labels: 📬 API, 🔨 Refactor

#114 Refactor: 카테고리 애니메이션 선택 안되는 오류 해결
  public/svgs/category/animationColor.svg
  public/svgs/category/animationGo.svg
  public/svgs/category/baseballGo.svg
  public/svgs/category/kpopGo.svg
  src/containers/category/Category.tsx
Labels: 🎨 Html & CSS, 🔨 Refactor

#116 Refactor: 입찰 리스트 데이터 패칭 진행중
  src/components/GoodsSummary/index.tsx
  src/containers/main/ComingSoon.tsx
  src/containers/main/Hits.tsx
  src/containers/mypage/BidList.tsx
  src/types/goodsApiDataType.ts
  src/utils/goodsApiActions.ts
Labels: 📬 API, 🎨 Html & CSS

#117 Feat: 알림 데이터 패칭, 삭제 기능 추가
  src/containers/main/notification/NotificationContent.tsx
  src/containers/main/notification/NotificationModal.tsx
  src/types/notiApiDataType.ts
  src/utils/notificationApiActions.ts
Labels: 📬 API, 🔨 Refactor

#120 Feat: 설정 페이지 구현
  src/app/(chat)/chat-room/[chatRoomId]/page.tsx
  src/app/mypage/notice/[noticeId]/page.tsx
  src/app/mypage/notice/page.tsx
  src/components/Btn/TogleSwitch.tsx
  src/components/Chat/Sending.tsx
  src/containers/chat/chat-list/ChatList.tsx
  src/containers/chat/chat-room/ChatView.tsx
  src/containers/chat/chat-room/_ChatSender.tsx
  src/containers/mypage/ActivityArea.tsx
  src/containers/mypage/AnnouncementArea.tsx
  src/containers/mypage/DuckPointArea.tsx
  src/containers/mypage/InfoArea.tsx
  src/containers/mypage/MannerDuckArea.tsx
  src/containers/mypage/NoticeList.tsx
  src/containers/mypage/NotificationArea.tsx
  src/containers/mypage/TradeArea.tsx
Labels: ✨ Feature

#121 Feat: 검색 기능 구현 완료
  .husky/pre-commit
  src/containers/main/search/RecentSearch.tsx
  src/containers/main/search/SearchForm.tsx
  src/containers/main/search/SearchResult.tsx
  src/containers/main/search/store.ts
  src/containers/member/login/LoginForm.tsx
  src/types/goodsType.ts
  src/types/headerType.ts
  src/types/readApiDataType.ts
  src/utils/readsApiActions.ts
Labels: 📬 API, 🐞 BugFix, ✨ Feature, 🎨 Html & CSS

#119 Refactor: 태그 정적으로 변경
  src/containers/goods/detail/DetailDescription.tsx
  src/containers/goods/registration/TagArea.tsx
  src/containers/main/TagItem.tsx
Labels: 🔨 Refactor

#122 Refactor: 검색 화면 수정, 굿즈 아이템 수정
  src/containers/goods/list/GoodsItem.tsx
  src/containers/goods/list/GoodsList.tsx
  src/containers/main/search/SearchForm.tsx
  src/containers/main/search/SearchModal.tsx
  src/utils/goodsListApiActions.ts
Labels: 🎨 Html & CSS, 🔨 Refactor

#123 Feat: 마이페이지 TradeArea
  public/sw.js
  public/workbox-dae32412.js
  src/app/mypage/bid/page.tsx
  src/app/mypage/like/page.tsx
  src/app/mypage/sell/page.tsx
  src/app/mypage/winning-bid/page.tsx
  src/components/GoodsSummary/index.tsx
  src/containers/mypage/bid/BidContent.tsx
  src/containers/mypage/bid/BidList.tsx
  src/containers/mypage/bid/BidTab.tsx
  src/containers/mypage/like/LikeItem.tsx
  src/containers/mypage/like/LikeList.tsx
  src/containers/mypage/sell/SellContent.tsx
  src/containers/mypage/sell/SellList.tsx
  src/containers/mypage/sell/SellTab.tsx
  src/containers/mypage/winning-bid/WinningBidList.tsx
  src/containers/mypage/winning-bid/WinningContent.tsx
  src/containers/mypage/winning-bid/WinningTab.tsx
  src/types/aggregationApiDataType.ts
  src/types/goodsApiDataType.ts
  src/types/readApiDataType.ts
  src/utils/goodsApiActions.ts
  src/utils/readsApiActions.ts
Labels: 📬 API, 🐞 BugFix, ✨ Feature, 🎨 Html & CSS

#124 Feat: 입찰자 없을 때 취소, 재등록 기능 구현
  public/sw.js
  public/workbox-b1b34251.js
  public/workbox-dae32412.js
  src/containers/goods/detail/ConfirmModal.tsx
  src/containers/goods/detail/ConfirmationBtn.tsx
  src/containers/goods/detail/DetailImageArea.tsx
Labels: 📬 API, ✨ Feature

#125 Fix: build error
  src/containers/mypage/bid/BidContent.tsx
  src/containers/mypage/sell/SellContent.tsx
  src/containers/mypage/winning-bid/WinningContent.tsx
Labels: 🐞 BugFix

#126 Fix: 토큰 리다이렉트 / 마이페이지 에러 + Refactor: 검색 기능 / 알림 페이지 개선
  public/sw.js
  public/workbox-b1b34251.js
  public/workbox-dae32412.js
  src/app/(main)/notification/page.tsx
  src/components/layout/Header.tsx
  src/components/layout/store.ts
  src/containers/complain/ComplainForm.tsx
  src/containers/goods/detail/BiddingModal.tsx
  src/containers/goods/detail/ToTalArea.tsx
  src/containers/goods/list/GoodsItem.tsx
  src/containers/goods/registration/GoodsForm.tsx
  src/containers/goods/registration/store.ts
  src/containers/main/LiveAndHotItem.tsx
  src/containers/main/notification/NotificationList.tsx
  src/containers/main/search/SearchForm.tsx
  src/containers/member/login/SocialForm.tsx
  src/containers/mypage/InfoArea.tsx
  src/containers/mypage/like/LikeItem.tsx
  src/containers/mypage/like/LikeList.tsx
  src/containers/mypage/sell/SellContent.tsx
  src/containers/mypage/update-profile/UpdateProfileForm.tsx
  src/types/goodsApiDataType.ts
  src/types/readApiDataType.ts
  src/utils/goodsApiActions.ts
  src/utils/readsApiActions.ts
Labels: 📬 API, 🐞 BugFix, ✨ Feature, 🔨 Refactor

#128 Refactor: 홈 화면 로컬스토리지 부분 수정 중, nav 수정, 등록 시 기간 에러 해결
  src/components/Header/MyPageHeader.tsx
  src/components/layout/Header.tsx
  src/components/layout/Nav.tsx
  src/containers/category/Category.tsx
  src/containers/category/CategorySelection.tsx
  src/containers/goods/detail/DetailHeader.tsx
  src/containers/goods/registration/PeriodArea.tsx
  src/containers/main/MainCategory.tsx
  src/containers/main/store.ts
Labels: 🐞 BugFix, 🔨 Refactor

#129 Feat: manifest.ts 수정 외
  src/app/manifest.ts
  src/containers/chat/chat-room/ChatViewReceiverCard.tsx
  src/containers/chat/chat-room/ChatViewSenderCard.tsx
  src/containers/chat/chat-room/_ChatSender.tsx
Labels: ✨ Feature

#130 Refactor: 홈 화면 속도 개선
  public/sw.js
  public/workbox-b1b34251.js
  public/workbox-dae32412.js
  src/containers/category/Category.tsx
  src/containers/goods/list/GoodsList.tsx
  src/containers/goods/registration/GoodsForm.tsx
  src/containers/main/MainCategory.tsx
Labels: 🔨 Refactor

#131 Refactor: css 일부 수정
  public/images/appleLoginBtn.png
  public/images/googleLoginBtn.png
  public/images/kakaoLoginBtn.png
  public/images/naverLoginBtn.png
  public/sw.js
  src/components/Chat/NickName.tsx
  src/containers/category/Category.tsx
  src/containers/chat/chat-list/LastChat.tsx
  src/containers/chat/chat-room/ChatView.tsx
  src/containers/goods/detail/DeleteBtn.tsx
  src/containers/main/MainCategory.tsx
  src/containers/member/login/LoginForm.tsx
  src/containers/member/login/SocialForm.tsx
Labels: 🐞 BugFix, 🔨 Refactor
